name = "goevergreen-worker"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[env.production]
route = "goevergreen.shop/*"

[[env.production.d1_databases]]
binding = "DB"
database_name = "goevergreen-db"
database_id = "your-database-id"

[env.development]
[[env.development.d1_databases]]
binding = "DB"
database_name = "goevergreen-db-dev"
database_id = "your-dev-database-id"

[vars]
ENVIRONMENT = "production"
DOMAIN = "goevergreen.shop"
CONTACT_EMAIL = "info@goevergreen.shop"