name = "worker-roue"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "goevergreen-db"
database_id = "4737589f-b16e-4f96-bc1b-0ad6b7ebc397"
# Environment variables
[vars]
ENVIRONMENT = "production"
DOMAIN = "goevergreen.shop"
CONTACT_EMAIL = "info@goevergreen.shop"
WORDPRESS_BASE_URL = "https://goevergreen9.wordpress.com"

# Build configuration for GUI deployment
[build]
command = "echo 'No build step required'"
