name = "worker-route"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "goevergreen-db"
# database_id will be automatically set by Cloudflare GUI when you bind the database

# Environment variables
[vars]
ENVIRONMENT = "production"
DOMAIN = "goevergreen.shop"
CONTACT_EMAIL = "info@goevergreen.shop"
WORDPRESS_BASE_URL = "https://goevergreen9.wordpress.com"

# Build configuration for GUI deployment
[build]
command = "echo 'No build step required'"
